layout: default
title: Interser
logo: /assets/img/logo.png
description: Interser e um espaço de reflexão sobre virtudes e valores bem como auto-conhecimento.
tagline: 'Interser'
url: "https://interser.github.io/"
comments: true
future: false
permalink: /posts/:title

plugins: [jekyll-seo-tag, jekyll-paginate, jekyll-watch, jekyll-sitemap]

paginate: 6

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap