layout: default
title: Raízes Perdidas
logo: /assets/img/logo.png
description: Raízes perdidas e um espaço de reflexão sobre virtudes e valores na vida de um ser humano.
tagline: 'Raízes Perdidas'
url: "https://raizesperdidas.github.io/"
comments: true
future: false
permalink: /posts/:title

plugins: [jekyll-seo-tag, jekyll-paginate, jekyll-watch, jekyll-sitemap]

paginate: 6

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap