layout: default
title: Interser Perdidas
logo: /assets/img/logo.png
description: Interser perdidas e um espaço de reflexão sobre virtudes e valores na vida de um ser humano.
tagline: 'Interser Perdidas'
url: "https://interser.github.io/"
comments: true
future: false
permalink: /posts/:title

plugins: [jekyll-seo-tag, jekyll-paginate, jekyll-watch, jekyll-sitemap]

paginate: 6

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap