baseURL = 'https://example.org/'
languageCode = 'pt-BR'
title = 'Interser'
theme = ["hugo-embed-pdf-shortcode", "ananke", "hugo-shortcode-roneo-collection"]
enableInlineShortcodes = true
enableRobotsTXT = true
[params]
  description = "Se você for um poeta, verá claramente que há uma nuvem flutuando nesta folha de papel. Sem uma nuvem, não haverá chuva; sem chuva, as árvores não podem crescer e, sem árvores, não podemos fazer papel. A nuvem é essencial para que o papel exista. Se ela não estiver aqui, a folha de papel também não pode estar aqui. Logo, nós podemos dizer que a nuvem e o papel intersão. “Interser” é uma palavra que não está no dicionário ainda, mas se combinarmos o prefixo “inter” com o verbo “ser”, teremos este novo verbo “interser”. Sem uma nuvem, não podemos ter papel, assim podemos afirmar que a nuvem e a folha de papel intersão."
  commentoEnable = false
  disqusShortname = ''
  text_color = "#FFF"
  author = ""
  favicon = ""
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5